apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: clickhouse-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-dockerhub-username/backend:latest
        ports:
        - containerPort: 5050
        env:
        - name: CLICKHOUSE_HOST
          value: "clickhouse"