apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: clickhouse-demo
spec:
  selector:
    app: clickhouse
  ports:
  - protocol: TCP
    port: 8123
    targetPort: 8123
  type: ClusterIP