apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: clickhouse-demo
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        sendfile on;

        server {
            listen 80;
            server_name _;

            root /usr/share/nginx/html;
            index index.html;

            location / {
                try_files $uri /index.html;
            }

            location /api/ {
                proxy_pass http://backend:5050/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            error_page 404 /index.html;
        }
    }
